export default {
  id: "zed",
  alias: "zed",
  uiAlias: "zed",
  display: {
    name: "Zed Hosted Models",
    icon: "code_blocks",
    color: "#101010",
    textIcon: "ZD",
    website: "https://zed.dev",
    notice: {
      signupUrl: "https://zed.dev",
      text: "Zed native sign-in currently redirects through GitHub. Sign out of Zed/GitHub or use a private browser window to switch accounts.",
    },
  },
  category: "oauth",
  authType: "oauth",
  authModes: ["oauth"],
  transport: {
    baseUrl: "https://cloud.zed.dev/completions",
    llmBaseUrl: "https://cloud.zed.dev",
    cloudBaseUrl: "https://cloud.zed.dev",
    webBaseUrl: "https://zed.dev",
    format: "openai",
    forceStream: true,
    timeoutMs: 120000,
    stallTimeoutMs: 120000,
    appVersion: "1.9.0",
  },
  models: [
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 1000000, maxOutputTokens: 128000, provider: "anthropic", supportsImages: true, supportsThinking: true },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", contextLength: 1000000, maxOutputTokens: 64000, provider: "anthropic", supportsImages: true, supportsThinking: true },
    { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", contextLength: 200000, maxOutputTokens: 8192, provider: "anthropic", supportsImages: true, supportsThinking: true },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", contextLength: 200000, maxOutputTokens: 64000, provider: "anthropic", supportsImages: true, supportsThinking: true },
    { id: "gpt-5.5", name: "GPT-5.5", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true, supportsThinking: true },
    { id: "gpt-5.4", name: "GPT-5.4", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true, supportsThinking: true },
    { id: "gpt-5.3-codex", name: "GPT-5.3-Codex", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true, supportsThinking: true },
    { id: "gpt-5.2", name: "GPT-5.2", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true },
    { id: "gpt-5.2-codex", name: "GPT-5.2-Codex", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true, supportsThinking: true },
    { id: "gpt-5-mini", name: "GPT-5 mini", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true },
    { id: "gpt-5-nano", name: "GPT-5 nano", contextLength: 400000, maxOutputTokens: 128000, provider: "openai", supportsImages: true },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro", contextLength: 200000, maxOutputTokens: 65535, provider: "google", supportsImages: true, supportsThinking: true },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", contextLength: 1048576, maxOutputTokens: 65535, provider: "google", supportsImages: true, supportsThinking: true },
    { id: "gemini-3-flash", name: "Gemini 3 Flash", contextLength: 1048576, maxOutputTokens: 65535, provider: "google", supportsImages: true, supportsThinking: true },
  ],
  oauth: {
    webBaseUrl: "https://zed.dev",
    cloudBaseUrl: "https://cloud.zed.dev",
    llmBaseUrl: "https://cloud.zed.dev",
    nativeSignInUrl: "https://zed.dev/native_app_signin",
    userInfoUrl: "https://cloud.zed.dev/client/users/me",
    llmTokenUrl: "https://cloud.zed.dev/client/llm_tokens",
    modelsUrl: "https://cloud.zed.dev/models",
    completionsUrl: "https://cloud.zed.dev/completions",
    defaultNativeAppPort: 58443,
  },
};
